### PR TITLE
feat: vote delegation

### PR DESCRIPTION
**Pull request by MarvinJanssen**
Simple all-or-nothing vote delegation. Users may register a delegate who can act on their behalf until explicitly revoked. It does not do anything fancy and required only a minimal intervention so I think this is a good addition to the reference implementation.

Users can only register one delegate at a time. Delegation is directly linked, so one cannot make delegation chains. (Which I think is desirable, as the user never chose to elect the third party delegate.)

@radicleart consider it a preamble the delegation concepts you are working on.

### CODE REVIEW

**Comment by MarvinJanssen** [comment]
I am thinking about ways in which we can make it so that the delegate does not have to send in a vote per delegatee. I created a "vote-many" equivalent but still do not like the amount of data to be posted. Perhaps a third sub token `edg-token-delegated` can solve it. Any suggestions welcome. I'm trying to keep the code succinct and clean.

**Comment by mijoco-btc** [comment]
For background there's a suggestion for such a mechanism here - [Proposal 2: New EDG Delegation Tokens](https://www.notion.so/claritylab/Executor-DAO-Delegated-Voting-081f05a7ad4940888fcca89266adb863) 

Also `feature/delegate-voting` has an implementation that tracks the delegated portion of edg using maps.

**Comment by mijoco-btc** [comment]
closing this here as it is now relevant to the EcosystemDAO repo

**Comment by MarvinJanssen** [comment]
@radicleart how about some sort of delegation mechanism for the reference repository?

**Pull request closed without merging**
