### PR TITLE
Treasury and token sale extensions

### PR DESCRIPTION
**Pull request by MarvinJanssen**
Work in progress.

### CODE REVIEW

**Comment by MarvinJanssen** [comment]
I changed the mechanism so that when tokens are bought, the sale contract immediately mints governance tokens to itself. They are then transferred when `claim` is called at the end of the sale. I decided to do it this way because then the entire bought supply will exist by the same the sale ends. The old way made it possible for an early token claimant to immediately submit a proposal and vote as the default mechanism requires a member to own X percent of the governance token to be able to submit a proposal. If the old contract were to be used for initial token issuance when launching a DAO, then the first claimant would temporarily own 100% of the token supply.

**Comment by mijoco-btc** [comment]
sounds safer.. i'll adjust the tests.

**Comment by mijoco-btc** [comment]
An interesting thing I'm finding in the tests is that when values are defined as uint constants and 0 has a special meaning in that 0 cause a different execution path from x > 0 then the tests are necessarily incomplete e.g.

```
(define-constant minimum-sale-amount u0) ;; Minimum number of tokens to sell for the sale to be successful.
(define-constant maximum-sale-amount u0) ;; Maximum number of tokens for sale, or 0 for no limit.
```

in ede007-governance-token-sale.clar 

Complete unit test coverage is not possible because you need to change the target code to cover all cases. 

I don't have the required test philosophy background to know how to handle this situation so I'd recommend we deploy this contract with 0 for these values - as tested - unless anyone knows how to handle this?

**Comment by MarvinJanssen** [comment]
Yep there is no way to deal with that situation with Clarinet at this point. I could turn them into data vars  that can be set via `start`.

**Comment by mijoco-btc** [comment]
Closing this here and moving it to EcosystemDAO

**Pull request closed without merging**
